---

# List handlers for Synapse
- name: Start synapse
  service: name=synapse state=started

- name: Stop synapse
  service: name=synapse state=stoped

- name: Restart synapse
  service: name=synapse state=restarted

# List handlers for Conky
- name: Start conky
  sudo: false
  shell: conky&