---
# This role deploys the mongodb processes and sets up settings.

- name: Mongodb | Add keys authenticity
  apt_key: url={{ url_apt_key }}0x7F0CEB10

- name: Mongodb | Add source sources
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/debian-sysvinit dist 10gen' update_cache=yes

- name: Mongodb | Install Packages
  apt: pkg=mongodb-10gen

- name: Mongodb | Install PHP 5 Mongo Module
  command: pecl install mongo creates=/usr/lib/php5/mongo/mongo.so
  ignore_errors: true

- name: Mongodb | Configure PHP to use PECL MongoDB extension
  template: src=etc-php5-conf-d-mongo-ini.j2 dest=/etc/php5/mods-available/mongo.ini

- name: Mongodb | Enable extension mongo.ini
  command: php5enmod ALL mongo state=present
