##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
- hosts: local
  user: lesmyrmidons
  sudo: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - common
    - vim
    - pinta
    - latex
    - nvidia
    - adst
    - web
    - mongodb
    - composer
    - nodejs
    - dotfile
