##
# Ansible playbook for setting up a LAMP development server on Ubuntu 12.04.
#

---
- hosts: local
  user: lesmyrmidons
  sudo: yes

  vars_files:
    - group_vars/all.yml

  roles:
    - common    # List of essential packages
    - vim       # Configuration for vim
    - pinta     # Gimp little
    - latex     # Latex and ide texmaker
    - nvidia    # Drivers owner
    - adst      # Application for series https://github.com/lesmyrmidons/AdstSF2
    - web
    - mongodb
    - composer
    - nodejs
    - dotfile   # My dotfile (config : git, zsh, bash, tig, ...)
    - gnome-shell
