---
# List handlers for Apache2

- name: Restart apache
  action: service name=apache2 state=restarted

- name: Graceful apache
  action: service name=apache2 state=graceful

- name: Start mariadb
  service: name=mysql state=started

- name: Stop mariadb
  service: name=mysql state=stoped

- name: Restart mariadb
  service: name=mysql state=restarted