---

- name: ADST | Clone project ADST
  sudo: false
  git: repo=git@github.com:lesmyrmidons/AdstSF2.git
       dest={{ web.project_path }}
       update=yes

- name: ADST | Set var for user apache
  sudo: false
  shell: echo `ps aux | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data' | grep -v root | head -1 | cut -d\  -f1`
  register: apache_user

- name: ADST | Application of the rights on folders 1
  shell: setfacl -R -m u:{{ apache_user.stdout }}:rwX -m u:`whoami`:rwX {{ web.project_path }}/app/cache {{ web.project_path }}/app/logs

- name: ADST | Application of the rights on folders 2
  shell: setfacl -dR -m u:{{ apache_user.stdout }}:rwX -m u:`whoami`:rwX {{ web.project_path }}/app/cache {{ web.project_path }}/app/logs