---

- name: Apache2 | Install required packages
  apt: pkg=apache2 state=installed
  tags: apache2

- name: Apache2 | Active module rewrite
  command: a2enmod rewrite 
  tags: apache2
  notify: Restart apache

- name: Apache2 | Add vhost for project adst
  template: src=vhost-sf2.conf.j2 dest=/etc/apache2/sites-available/{{ web.domain }}.conf
  tags: apache2

- name: Apache2 | Activate vhost
  command: a2ensite {{ web.domain }}.conf
  tags: apache2
  notify: Restart apache

- action: file state=absent path=/etc/apache2/sites-enabled/000-default
  notify:
    - restart apache

# This role deploys the MariaDB processes and sets up settings.

- name: MariaDB | Add keys authenticity
  apt_key: url={{ url_apt_key }}0xcbcb082a1bb943db state=present

- name: MariaDB | Add source sources
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/10.0/debian wheezy main' update_cache=yes

- name: MariaDB | Install Packages
  apt: pkg={{ item }} state=installed
  with_items:
    - mariadb-server
    - python-mysqldb
  notify: Start mariadb

- name: MariaDB | Update mysql root password for all root accounts from local servers
  mysql_user: login_user=root 
              login_password={{ mariadb.current_password }}
              name=root
              host={{ item }}
              password={{ mariadb.root_password }}
              priv=*.*:ALL,GRANT
  with_items:
    - $ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost
  notify: Restart mariadb

- name: MariaDB | Write file my.cnf
  template: src=templates/my.cnf.j2 dest=/root/.my.cnf

# This role deploys the PHP5 processes and sets up settings.

- name: PHP5 | Install required packages.
  action: apt pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-dev
    - php-pear
    - php5-ldap
    - php5-curl
    - php5-intl
    - php5-cli
    - php5-xdebug
    - php5-mysql
  tags: php5
  notify: Restart apache

- name: PHP5 | Configuration /etc/php5/apache2/php.ini
  template: src=etc-php5-apache2-php-ini.j2 dest=/etc/php5/apache2/php.ini mode=0644
  notify: Restart apache

- name: PHP5 | Configuration /etc/php5/cli/php.ini
  template: src=etc-php5-cli-php-ini.j2 dest=/etc/php5/cli/php.ini mode=0644

- name: PHP5 | PHPDev | Update pear packages
  command: pear upgrade

- name: PHP5 | PHPDev | Update pear packages
  command: pear upgrade

- name: PHP | PHPDev | Set pear auto-discover
  command: pear config-set auto_discover 1

- name: PHP | PHPDev | Pear install the PHP QA Toolchain
  command: pear install pear.phpqatools.org/phpqatools creates=/usr/bin/phpunit
  # this fails often (dns problems, pear problems, etc. So just ignore the errors and continue.)
  ignore_errors: true