---
# This playbook contains common plays that will be run on all nodes.

- name: NTP | Install
  apt: name=ntp state=present
  tags: ntp

- name: NTP | Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: NTP | Start the ntp service
  service: name=ntp state=started enabled=true
  tags: ntp

- name: Linux | Update cache
  apt: update_cache=yes

- name: Linux | Upgrade
  apt: upgrade=dist

- name: Package | Install lists packages
  action: apt pkg=$item state=installed
  with_items:
    - aptitude
    - vim
    - git
    - zsh
    - curl
    - wget
    - htop
    - ack-grep
    - ccze

- name: Java Oracle | Add repository
  apt_repository: repo='ppa:webupd8team/java'

- name: Java Oracle | Install version 1.7.x
  apt: name=oracle-java7-installer state=installed

- name: Virtualbox | Add repository
  apt_repository: repo='deb http://download.virtualbox.org/virtualbox/debian saucy contrib' state=present

- name: Virtualbox | Add key
  apt_key: url='http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc' state=present

- name: Virtualbox | Install Virtualbox v4.3.x
  apt: name=virtualbox-4.3 state=installed