---

# Synapse Noobslab repository
- name: "Launcher | Add repository Synapse via noobslab"
  apt_repository: repo='ppa:noobslab/apps' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and {{ ansible_distribution_version | version_compare('14.04', '<') }}

- name: "Launcher | Install Synapse via noobslab"
  apt: pkg={{ item }} state=installed
  when: ansible_distribution == "Ubuntu" and {{ ansible_distribution_version | version_compare('14.04', '<') }}
  with_items:
    - synapse
    - indicator-synapse
  notify:
    - Start synapse

# Synapse Official repository
- name: "Launcher | Add repository Synapse"
  apt_repository: repo='ppa:synapse-core/testing' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and {{ ansible_distribution_version | version_compare('14.04', '>=') }}

- name: "Launcher | Install Synapse"
  apt: pkg={{ item }} state=installed
  when: ansible_distribution == "Ubuntu" and {{ ansible_distribution_version | version_compare('14.04', '>=') }}
  with_items:
    - synapse
  notify:
    - Start synapse

- name: "Launcher | Set configuration"
  copy: src=config.json dest=/home/{{ user }}/.config/synapse/config.json owner={{ user }} group={{ user }} mode=664
