---

# 
- name: "Launcher | Add repository Synapse"
  apt_repository: repo='ppa:noobslab/apps' state=present update_cache=yes
  when: ansible_distribution == "Ubuntu" and {{ ansible_distribution_version | version_compare('14.04', '<') }}

- name: "Launcher | Install Synapse"
  apt: pkg={{ item }} state=installed
  when: ansible_distribution == "Ubuntu" and {{ ansible_distribution_version | version_compare('14.04', '<') }}
  with_items:
    - synapse
    - indicator-synapse
  notify:
    - Start synapse

# Install PhpStorm
- name: "PhpStorm | Download application in zip"
  sudo: false
  get_url: url=http://www.jetbrains.com/phpstorm/download/download_thanks.jsp?os=linux dest=/home/{{ user }}/phpstorm.tar.gz

- name: "PhpStorm | Unarchive application and move into folder /opt"
  unarchive: src=/home/{{ user }}/phpstorm.tar.gz dest=/opt/phpstorm
  ignore_errors: true

# 
- name: Clone dotfile repo
  sudo: false
  git: repo=git@github.com:lesmyrmidons/dotfiles.git dest=/home/{{ user }}/.dotfiles update=yes
